apiVersion: v1
kind: ConfigMap
metadata:
  name: wikibench-env-config
data:
  TRACE_DIR_PATH: "./../mnt/trace/"
  TARGET_URL: "http://productpage.default.svc.cluster.local:9080/productpage?u=normal"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wikibench-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/data/wikibench"  # path in Minikube VM
  storageClassName: manual

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikibench-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikibench
  labels:
    app: wikibench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikibench
  template:
    metadata:
      labels:
        app: wikibench
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.tcp_tw_reuse
            value: "1"
          - name: net.ipv4.tcp_timestamps
            value: "1"
      containers:
        - name: wikibench
          image: daffarg/wikibench-request-generator:v1.18
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: wikibench-env-config
          volumeMounts:
            - mountPath: /mnt/trace
              name: wikibench-volume
      volumes:
        - name: wikibench-volume
          persistentVolumeClaim:
            claimName: wikibench-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: wikibench
spec:
  type: NodePort
  selector:
    app: wikibench
  ports:
    - port: 3000
      targetPort: 8080
      nodePort: 30000
