apiVersion: v1
kind: ConfigMap
metadata:
  name: wikibench-env-config
data:
  TRACE_FILE_URL: "https://storage.googleapis.com/tesis-cb-drl/trace/example.trace"
  TARGET_URL: "http://productpage.default.svc.cluster.local:9080/productpage?u=normal"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikibench
  labels:
    app: wikibench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikibench
  template:
    metadata:
      labels:
        app: wikibench
    spec:
      containers:
        - name: wikibench
          image: daffarg/wikibench-request-generator:v1.2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: wikibench-env-config

---

apiVersion: v1
kind: Service
metadata:
  name: wikibench
spec:
  type: NodePort
  selector:
    app: wikibench
  ports:
    - port: 3000
      targetPort: 8080
      nodePort: 30000